name: Build Rust
on:
  workflow_call:

jobs:
  windows-bins:
    runs-on: windows-latest
    env:
      RUSTFLAGS: -C target-feature=+crt-static
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Job Environment
        uses: ./.github/actions/job-setup
        with:
          rust-cache: true
      - name: Install Dependencies
        run: |
          rustup component add rust-src --toolchain nightly-x86_64-pc-windows-msvc
      - name: Build Rust Binaries
        run: cargo +nightly build --target i686-win7-windows-msvc --features windows --release -Z build-std="core,alloc,std,panic_abort" -p velopack_bins
      - name: Upload Rust Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rust-windows-bins
          path: |
            target\i686-win7-windows-msvc\release\*.exe
            target\i686-win7-windows-msvc\release\*.pdb
          retention-days: 1

  windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        target: [x86, x64, arm64]
        include:
          - target: x86
            rust_flags: --release -Z build-std="core,alloc,std,panic_abort"
            rust_target: i686-win7-windows-msvc
          - target: x64
            rust_flags: --release -Z build-std="core,alloc,std,panic_abort"
            rust_target: x86_64-win7-windows-msvc
          - target: arm64
            rust_flags: --release
            rust_target: aarch64-pc-windows-msvc
    env:
      RUSTFLAGS: -C target-feature=+crt-static
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Job Environment
        uses: ./.github/actions/job-setup
        with:
          rust-cache: true
      - name: Install Dependencies
        run: |
          rustup component add rust-src --toolchain nightly-x86_64-pc-windows-msvc
          rustup target add aarch64-pc-windows-msvc --toolchain nightly-x86_64-pc-windows-msvc
      - name: Build Rust (${{ matrix.target }})
        run: |
          cargo +nightly build --target ${{ matrix.rust_target }} ${{ matrix.rust_flags }} -p velopack_nodeffi -p velopack_libc
          move target\${{ matrix.rust_target }}\release\velopack_nodeffi.dll target\velopack_nodeffi_win_${{ matrix.target }}_msvc.node 
          move target\${{ matrix.rust_target }}\release\velopack_libc.dll target\velopack_libc_win_${{ matrix.target }}_msvc.dll
          move target\${{ matrix.rust_target }}\release\velopack_libc.dll.lib target\velopack_libc_win_${{ matrix.target }}_msvc.dll.lib
          move target\${{ matrix.rust_target }}\release\velopack_libc.lib target\velopack_libc_win_${{ matrix.target }}_msvc.lib
      - name: Upload Rust Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rust-windows-libs-${{ matrix.target }}
          path: |
            target\*.node
            target\*.dll
            target\*.lib
          retention-days: 1
      - name: Cancel workflow if failed
        uses: andymckay/cancel-action@0.5
        if: ${{ failure() }}
